version: "3.9"

services:
  scanner:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOURPASS
      - POSTGRES_DB=contracts

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOURPASS
      POSTGRES_DB: contracts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
